name: Deploy to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Replicate registry
        run: |
          echo "${{ secrets.REPLICATE_API_TOKEN }}" | docker login r8.im -u leizeng --password-stdin

      - name: Setup Cog
        uses: replicate/setup-cog@main
        with:
          replicate_api_token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build and push
        run: |
          cog build -t r8.im/leizeng/z-image-turbo
          docker push r8.im/leizeng/z-image-turbo:latest
